// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCv4HrMzQxXLQ9I0ueDa4HTL7mwbq8vKE',
    appId: '1:529381198955:web:d4194799a4f1475d4e752e',
    messagingSenderId: '529381198955',
    projectId: 'mallige-e252b',
    authDomain: 'mallige-e252b.firebaseapp.com',
    storageBucket: 'mallige-e252b.appspot.com',
    measurementId: 'G-EKPW2G271F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVf2xOAdfnZHhV41WC5czO6Tu_GJkiiA',
    appId: '1:529381198955:android:77d8bee696349e8d4e752e',
    messagingSenderId: '529381198955',
    projectId: 'mallige-e252b',
    storageBucket: 'mallige-e252b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25Sk5gN9d4c2lv06GaE3g4xhecbZt8mo',
    appId: '1:529381198955:ios:a698b0f74424475b4e752e',
    messagingSenderId: '529381198955',
    projectId: 'mallige-e252b',
    storageBucket: 'mallige-e252b.appspot.com',
    iosBundleId: 'com.example.mallige',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25Sk5gN9d4c2lv06GaE3g4xhecbZt8mo',
    appId: '1:529381198955:ios:bfceccaddac9ae484e752e',
    messagingSenderId: '529381198955',
    projectId: 'mallige-e252b',
    storageBucket: 'mallige-e252b.appspot.com',
    iosBundleId: 'com.example.mallige.RunnerTests',
  );
}
